sudo: false
language: objective-c
osx_image: xcode7.3
xcode_workspace: LDSAnnotations.xcworkspace
xcode_scheme: LDSAnnotations
xcode_sdk: iphonesimulator9.3
env:
  global:
    secure: aIVRtv1Uh3h3ouRk7jdzVFO1eSw+yZECPlTUPQDYywmVTfCGInpm3QlrYhJiJ6U/qsK5dlLyOHCcGVudBF8Qy2CfBg+wAX6IC+tKbVlZrOJsPFPMMavUXFMc/tcmiKQkv6fSjovEHZGtSPjJ8GM+jP4Ar+Xi78nqNmG6TdB9ibn1Hb9lX35Jw9AvKdkPpMJTdeJQ/RPiPVgo80P8po0jihb7ry/pX1pMZuVvkDmlWcEP6L1p5JKOOTd94HpRaSDCdTyTp3K/URkgrMOzTg23xpDCcgQ5roZLSJnUSEEo2XaOSeROjR6NtkBsHYrvaLgsdxzMRy34sbtthNmg/DhDMCFtL5hN3KDLSWmKHwa4TKKd+QltGTiwAM01Hg9ABPHXBxd6v40sGGNeFcWcBHbUxwhL0/jXM6MNqdEBBmIcHzn/TAO5bnkPvgJHpyryZDR7MuvuFtSnArzUnR61k031U9FNHg4Jx85Yehh/1sj7wI38szvOdo+nx4dvkA/32zG9B3ioZ9RIEhA2mUzca/rrQHRF5mw6hxVswzpqf9JliceT9Otapfat+iDe0jcDUfp/Zk7AwxMp6UjV8RiaBnkbY3xaREbytgW2Kf9RDxKWAh1qvyurz2gkxrW6ZIZ3QmEp/EMP7mhHK/znE/tTLt7QEc6+bCmXF4AEXeKtot+vZVY=
